id: A24B85B28
title: 'Zabchema: Profound Cure, The Practice of Bhaiṣajya-Guru, Lord of Physicians'
type: translation
pechas:
- IECA5F3E3
- I209C2537
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:45:40.955547
  last_modified_at: 2023-01-04 12:45:40.955566
  collections:
  - Karma Chakme Series
  - Works of Tibetan Masters
alignment_to_base:
  IECA5F3E3/4F3D: 0A58
  I209C2537/AB9A: 0A58
